[theme]
primaryColor = "#FF6B00"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#FFFFFF"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true
enableCORS = false
port = 8501